services:
  meganode:
    image: alpine:3.20
    container_name: gateway-meganode
    command: ["sh", "-c", "echo Mega-Node stub up; tail -f /dev/null"]
    restart: unless-stopped

  gateway:
    container_name: gateway-container
    build:
      context: ../
      dockerfile: deploy/scripts/Dockerfile.ai
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    restart: no
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - WATCHFILES_FORCE_POLLING=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ../:/app
      - venv-cache:/app/.venv
    command: >
      bash -lc 'uv sync --frozen || uv sync; uv run uvicorn backend.main:app --host 0.0.0.0 --port 8080 --reload --reload-dir /app/backend --reload-include "*.py" --no-access-log'


volumes:
  venv-cache:
